<a href="https://colab.research.google.com/github/dfvesgao/MetNumUN2023I/blob/main/Quiz1/dfvesgao_Quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


This quiz was created originaly in:

- Python 3.6.9

- NumPy: 1.19.5

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzz(x):
  if(x%3==0 and x%5!=0):
      answer ="Fizz!"
  elif(x%3!=0 and x%5==0):
      answer ="Buzz!"
  elif(x%3==0 and x%5==0):
      answer ="FizzBuzz!"
  else:
      answer ="..."
  return answer


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [ ]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

## **2. *FizzBuzzList*  - Python**
---

Write the function *FizzBuzzList* that returns a list with the answers of *FizzBuzz* for the integer numbers $1$ to $n$ (including $n$).

---

###**Problem Description**

**Task:** Given an integer $n$ return the list with the *FizzBuzz* answers for the integer numbers $1$ to $n$ (including $n$).
  

**Input Format:** The input consists of a single integer $n$. 

**Constraints:** $n$ is an integer

**Output Format:**  list with the *FizzBuzz* answers, if the input is not positive return an empty list.

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    ans = []
    for i in range(n):
      ans.append(FizzBuzz(i+1))
    return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [ ]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

## **3. *Standarize* - z scores - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** functions ***`mean`*** and ***`std`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [ ]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


---

###**Problem Description**

**Task:** Given an numpy array $X$ return the corresponding standard scores.
  
**Input Format:** The input consists of a numpy array $X$. 

**Output Format:**  A numpy array with standard scores corresponding to $X$.

**Solution**

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = ((X-X.mean())/X.std())
  return X_standarized

## **4. *Main diagonal matrix*  - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** function ***`diag`***  and ***`astype`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [ ]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


---

###**Problem Description**

**Task:** Given a numpy matrix $A$ (2-D array) return the diagonal matrix with the elements of its main diagonal.
 

**Input Format:** The input consists of a numpy matrix $A$ (2-D array).

**Output Format:**  The diagonal matrix with the elemnts of its main diagonal.

**Sample testcases**

```python
#run this sample testcases to help you validate your solution

A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

A = np.array([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]
    
])
main_diagonal_matrix(A)
#  --> Expected output: 
array([[4., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.]])
```
---

In [ ]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float)
  return D

**¡Congratulations!** You have finished your first quiz.

